---
  - name: Training_Containers
    hosts: app_servers
    gather_facts: False
    remote_user: ubuntu
    tasks: 
      - name: Ensure docker-compose directory exists
        file:
          path: /home/ubuntu/src/docker-compose/training/
          state: directory
      - name: Ensure docker-compose file is up to date
        template:
          src: training/docker-compose.yml
          dest: "/home/ubuntu/src/docker-compose/training/docker-compose.yml"
      - name: Stop the containers
        command: /usr/local/bin/docker-compose -f /home/ubuntu/src/docker-compose/training/docker-compose.yml down
      - name: Start the containers
        command: /usr/local/bin/docker-compose -f /home/ubuntu/src/docker-compose/training/docker-compose.yml up -d
